language: node_js
node_js:
  - 6.1
  - 6.0
  - 5.11
  - 5.0
  - 4.4
  - 4.0
notifications:
  slack: newmips:65VDeyCjdGVrhnr2VFOXnL1g
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
