version: '2'
services:
  dbseed:
    build:
      context: sql
    image: dbseed
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=newpass
      - MYSQL_USER=newmips
      - MYSQL_PASSWORD=newmips
      - MYSQL_DATABASE=newmips
    ports: 
      - 3306:3306
    volumes_from:
      - dbseed
    volumes:
      - dbdata:/var/lib/mysql
  newmips:
    build:
      context: .
      dockerfile: Dockerfile 
    image: newmips
    ports: 
      - 1337:1337
    links: [ mysql ]
volumes:
  -dbdata:/usr/local/docker/data