version: '2'
services:
  dbseed:
    build:
      context: sql
    image: dbseed
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=newpass
      - MYSQL_USER=newmips
      - mYSQL_PASSWORD=newmips
    ports: 
      - 3306:3306
    volumes_from:
      - dbseed
  newmips:
    build:
      context: .
    image: newmips
    ports: 
      - 1337:1337
    links: [ mysql ]
      